[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"

[lib]
bench = true

[dependencies]
aoc-parse = "0.2.18"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
maplit = "1.0.2"
rust-crypto = "0.2.36"
